name: CI-CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Docker
        run: docker build -t todo-backend ./TodoSummaryAssistant-main/Backend/todo-summary-assistant

      - name: Build Frontend Docker
        run: docker build -t todo-frontend ./TodoSummaryAssistant-main/Frontend/todo

      - name: Success
        run: echo "Build passed!"
